### ISSUE TITLE
The CSV is not working

### ISSUE THREAD

**Issue by azizirac** [alex-wilson-gwf/gmapsjson#1]
Hi, let me start saying that this is awesome. I tried to upload the existing styles are work perfectly.

I tried to use the converter and I couldn't make it work. Even using the example in there. See screenshots. I wanted to test it with https://snazzymaps.com/style/1243/xxxxxxxxxxx

![Screenshot 2024-10-25 at 21 20 16](https://github.com/user-attachments/assets/bb20db18-8cfa-45b9-99f2-2072635e1018)
![Screenshot 2024-10-25 at 21 20 12](https://github.com/user-attachments/assets/c287e013-baab-4879-be2e-726fa238f15d).

**Comment by morceaudebois** [comment]
Having the same problem here, it all says `#NAME` in the output tab and it doesn't seem to work like in the video. I think I did all the previous steps correctly and tried multiple times.

Did you end up finding a way @azizirac?

**Comment by alex-wilson-gwf** [comment]
> Having the same problem here, it all says `#NAME` in the output tab and it doesn't seem to work like in the video. I think I did all the previous steps correctly and tried multiple times.
> 
> Did you end up finding a way @azizirac?

Let me take a look. Can you send me a link to the template you’re trying to convert please?

**Comment by alex-wilson-gwf** [comment]
> Hi, let me start saying that this is awesome. I tried to upload the existing styles are work perfectly.
> 
> I tried to use the converter and I couldn't make it work. Even using the example in there. See screenshots. I wanted to test it with https://snazzymaps.com/style/1243/xxxxxxxxxxx
> 

@azizirac  Sorry about this. And sorry for lack of response, I didn’t get a notification on this one.

**Comment by morceaudebois** [comment]
That would be this one: https://snazzymaps.com/style/60952/apple-like

Thank you!

**Comment by alex-wilson-gwf** [comment]
> That would be this one: https://snazzymaps.com/style/60952/apple-like
> 
> Thank you!

@morceaudebois 

**Here's the modified JSON:**

`{\"featureType\":\"poi.emergency\",\"elementType\":\"geometry\",\"stylers\":[{\"color\":\"#fbd3da\"}]},
{\"featureType\":\"poi.outdoor_area_or_point.park\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#b0e9ac\"}]},
{\"featureType\":\"poi.outdoor_area_or_point.sports_complex\",\"elementType\":\"geometry\",\"stylers\":[{\"color\":\"#c3eb9a\"}]},
{\"featureType\":\"transportation.road.normal_segment.arterial\",\"elementType\":\"geometry\",\"stylers\":[{\"color\":\"#fed7a5\"}]},
{\"featureType\":\"transportation.built_up_area\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#fbf5ed\"}]},
{\"featureType\":\"land.water\",\"elementType\":\"geometry\",\"stylers\":[{\"color\":\"#a4e1ff\"}]},
{\"featureType\":\"land.background\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#fbf5ed\"}]},
{\"featureType\":\"poi.transit_poi.airport\",\"elementType\":\"geometry.fill\",\"stylers\":[{\"color\":\"#dee3fb\"}]},
{\"featureType\":\"transportation.road.normal_segment.arterial\",\"elementType\":\"geometry.fill\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#fbe38b\"}]},
{\"featureType\":\"transportation.road.normal_segment.high_priority\",\"elementType\":\"geometry.fill\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#ffe523\"}]},
{\"featureType\":\"transportation.road.normal_segment.local_or_overpass\",\"elementType\":\"geometry.fill\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#ffffff\"}]},
{\"featureType\":\"transportation.road\",\"elementType\":\"geometry.stroke\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#e7ded6\"}]},
{\"featureType\":\"transportation.road.normal_segment.high_priority\",\"elementType\":\"geometry.stroke\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#fbc28b\"}]},
{\"featureType\":\"transportation.road.normal_segment.local_or_overpass\",\"elementType\":\"geometry.stroke\",\"stylers\":[{\"visibility\":\"on\"},{\"weight\":0.50}]},
{\"featureType\":\"poi\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"poi.emergency\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"on\"}]},
{\"featureType\":\"poi.entertainment\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"on\"}]},
{\"featureType\":\"poi.outdoor_area_or_point.park\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"on\"}]},
{\"featureType\":\"poi.retail\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"poi.services\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"transportation.road\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"on\"}]},
{\"featureType\":\"transportation.road.normal_segment.high_priority\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"on\"}]},
{\"featureType\":\"administrative.top_level_admin\",\"elementType\":\"labels.text.fill\",\"stylers\":[{\"color\":\"#796340\"}]}`

One of my steps was horribly unclear. I'll update it now, and update the Excel template in a few minutes.

![applelike](https://github.com/user-attachments/assets/32e9ffa0-8c93-4c62-b86f-4bfd0b6303f3)

**Comment by alex-wilson-gwf** [comment]
I've updated the Excel sheet in the repo, and added worked example
@azizirac @morceaudebois

**Comment by alex-wilson-gwf** [comment]
@azizirac I'm probably too late, but here's the JSON the spreadsheet gives for that snazzy map:

`{\"featureType\":\"poi\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"administrative\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"transportation\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"transportation.road\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"on\"},{\"color\":\"#000000\"}]},
{\"featureType\":\"land\",\"elementType\":\"geometry\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"poi\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"administrative\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"transportation\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"off\"}]},
{\"featureType\":\"land\",\"elementType\":\"labels\",\"stylers\":[{\"visibility\":\"off\"}]}`

I'm not sure it works for this one though.  It's coming out like this:

![interfacemap](https://github.com/user-attachments/assets/f8d97698-b118-4d92-a28f-d3dc73d67af7)

**Comment by alex-wilson-gwf** [comment]
@azizirac @morceaudebois what version of Excel are you using?  The formuals rely on the LET function which is only available in Office 365: https://support.microsoft.com/en-au/office/let-function-34842dd8-b92b-4d3f-b325-b8b8f9908999

**Comment by morceaudebois** [comment]
Oh my it worked! Thank you so much @alex-wilson-gwf, absolutely ridiculous that we have to do this kind of manipulation, but I'm glad you took the time to document it properly.

> @azizirac @morceaudebois what version of Excel are you using? The formuals rely on the LET function which is only available in Office 365: https://support.microsoft.com/en-au/office/let-function-34842dd8-b92b-4d3f-b325-b8b8f9908999

I'm using an old pirated version (16.45) on macOS, so makes sense that it didn't work.
